作業目標<br>
熟悉陣列維度轉換，並且會擷取需要資料<br>
作業重點<br>
使用reshap須注意order用法<br>
where可以運用邏輯條件擷取資料

題目:<br>
1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")<br>
2.呈上題的array，找出被6除餘1的數的索引<br>

In [6]:
import numpy as np

In [7]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30)).reshape(5,6,order='F')
print('Oringianl Array: \n',array1)

Oringianl Array: 
 [[ 0  5 10 15 20 25]
 [ 1  6 11 16 21 26]
 [ 2  7 12 17 22 27]
 [ 3  8 13 18 23 28]
 [ 4  9 14 19 24 29]]


In [8]:
#2.呈上題的array，找出被6除餘1的數的索引
'''
#找出陣列中，除6餘1的數(回傳值為index),並將index轉換為二維陣列
np.where(array1%6==1)
'''
index_arr = np.vstack(np.where(array1%6==1))

In [9]:
'''
# 利用陣列分割，找出數字在array1的位置,array1[row][column]
np.split(index_arr,5,axis=1)  #切割陣列為1x2，代表[row,column]
'''
for row in np.split(index_arr,5,axis=1):  # 取出1x2 陣列(row)
    indx_row = int(row[0])
    indx_column = int(row[1])
    print(f'被6除餘1的數為: {array1[indx_row][indx_column]}, 索引位置：{row[0]},{row[1]}')

被6除餘1的數為: 25, 索引位置：[0],[5]
被6除餘1的數為: 1, 索引位置：[1],[0]
被6除餘1的數為: 7, 索引位置：[2],[1]
被6除餘1的數為: 13, 索引位置：[3],[2]
被6除餘1的數為: 19, 索引位置：[4],[3]
