# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [1]:
# 記得先 Import 正確的套件
import numpy as np
import random

In [23]:
array = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)

In [24]:
%timeit -n 10 a = 2
# 方法一
print(array+1)

32.9 ns ± 14.1 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)
[[[ 7  8  1 ...  7  5  8]
  [ 9 10  8 ...  8  6  9]
  [ 4 10 10 ...  1  5  7]
  ...
  [10  4  1 ...  5  8  8]
  [ 8 10  2 ...  4  2  2]
  [ 9  3  3 ...  1  9 10]]

 [[ 3  7  7 ...  6  8  9]
  [ 6  1  8 ...  4  3  6]
  [ 8  7  3 ...  6 10  8]
  ...
  [ 2  5  4 ...  6  6  2]
  [ 8  3  7 ...  9  8 10]
  [ 5 10  1 ...  8  2  6]]

 [[ 7  6  7 ...  7  2  8]
  [10 10  8 ...  6  2  7]
  [ 1  7  6 ...  2 10  5]
  ...
  [10  2  6 ...  1  4  3]
  [ 1  4  2 ...  3  5  9]
  [ 9  9  1 ...  8  6  4]]

 ...

 [[ 7  7  2 ...  6  6  5]
  [ 1 10  4 ...  2  6  3]
  [ 5 10  8 ...  2  1  4]
  ...
  [ 2  5 10 ...  3  5  6]
  [10  8  7 ...  3  9  1]
  [10  7  8 ...  7  2  9]]

 [[ 8  6  3 ...  3  4  2]
  [ 5  1  8 ...  2  3  7]
  [ 4  1  3 ...  3  9  3]
  ...
  [ 1  9  5 ...  4  7 10]
  [ 2  7  3 ...  2  6  4]
  [ 7  3  4 ...  6  4  2]]

 [[ 7 10  8 ...  2  4  4]
  [ 8  6  3 ...  3  7  5]
  [ 1  4  4 ...  9  5  5]
  ...
  [ 1  5  7 ...  1 

In [25]:
%timeit -n 10 a = 2
# 方法二
count =0
temp_array = np.empty(1000000)
for i  in array.flatten():
    temp_array[count] = i+1
    count +=1
temp_array.reshape(100,100,100)

36.6 ns ± 13.2 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 7.,  8.,  1., ...,  7.,  5.,  8.],
        [ 9., 10.,  8., ...,  8.,  6.,  9.],
        [ 4., 10., 10., ...,  1.,  5.,  7.],
        ...,
        [10.,  4.,  1., ...,  5.,  8.,  8.],
        [ 8., 10.,  2., ...,  4.,  2.,  2.],
        [ 9.,  3.,  3., ...,  1.,  9., 10.]],

       [[ 3.,  7.,  7., ...,  6.,  8.,  9.],
        [ 6.,  1.,  8., ...,  4.,  3.,  6.],
        [ 8.,  7.,  3., ...,  6., 10.,  8.],
        ...,
        [ 2.,  5.,  4., ...,  6.,  6.,  2.],
        [ 8.,  3.,  7., ...,  9.,  8., 10.],
        [ 5., 10.,  1., ...,  8.,  2.,  6.]],

       [[ 7.,  6.,  7., ...,  7.,  2.,  8.],
        [10., 10.,  8., ...,  6.,  2.,  7.],
        [ 1.,  7.,  6., ...,  2., 10.,  5.],
        ...,
        [10.,  2.,  6., ...,  1.,  4.,  3.],
        [ 1.,  4.,  2., ...,  3.,  5.,  9.],
        [ 9.,  9.,  1., ...,  8.,  6.,  4.]],

       ...,

       [[ 7.,  7.,  2., ...,  6.,  6.,  5.],
        [ 1., 10.,  4., ...,  2.,  6.,  3.],
        [ 5., 10.,  8., ...,  2.,  1.,  4.

In [26]:
%timeit -n 10 a = 2
#方法三
np.add(array,1)

35.7 ns ± 14.4 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


array([[[ 7,  8,  1, ...,  7,  5,  8],
        [ 9, 10,  8, ...,  8,  6,  9],
        [ 4, 10, 10, ...,  1,  5,  7],
        ...,
        [10,  4,  1, ...,  5,  8,  8],
        [ 8, 10,  2, ...,  4,  2,  2],
        [ 9,  3,  3, ...,  1,  9, 10]],

       [[ 3,  7,  7, ...,  6,  8,  9],
        [ 6,  1,  8, ...,  4,  3,  6],
        [ 8,  7,  3, ...,  6, 10,  8],
        ...,
        [ 2,  5,  4, ...,  6,  6,  2],
        [ 8,  3,  7, ...,  9,  8, 10],
        [ 5, 10,  1, ...,  8,  2,  6]],

       [[ 7,  6,  7, ...,  7,  2,  8],
        [10, 10,  8, ...,  6,  2,  7],
        [ 1,  7,  6, ...,  2, 10,  5],
        ...,
        [10,  2,  6, ...,  1,  4,  3],
        [ 1,  4,  2, ...,  3,  5,  9],
        [ 9,  9,  1, ...,  8,  6,  4]],

       ...,

       [[ 7,  7,  2, ...,  6,  6,  5],
        [ 1, 10,  4, ...,  2,  6,  3],
        [ 5, 10,  8, ...,  2,  1,  4],
        ...,
        [ 2,  5, 10, ...,  3,  5,  6],
        [10,  8,  7, ...,  3,  9,  1],
        [10,  7,  8, ...,  7,  2

### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [27]:

Z = np.random.randint(0,10,50)
print(Z)


[6 7 0 2 8 3 2 7 2 3 6 9 5 9 6 7 5 1 9 4 3 4 0 2 8 3 5 8 9 3 8 6 3 2 9 8 0
 5 6 4 0 8 4 8 1 0 6 9 4 4]


In [34]:
def Add_dict(dict,key,count):
    if key not in dict:
        dict[key] = " "
    dict[key] = count
    
count_dict = {}
for num in Z:
    count =0
    for i in range(len(Z)):
        if num == Z[i]:
            count +=1
    Add_dict(count_dict,num,count)
    
#找出眾數
for key in count_dict:
    if count_dict[key] == max(count_dict.values()):
        mode = key
print(f'眾數為: {mode}，出現次數： {max(count_dict.values())}次')

眾數為: 8，出現次數： 7次


In [35]:
# 眾數出現在數列的位置
for index in range(len(Z)):
    if Z[index] == mode:
        print(f'出現眾數{mode} 的位置： {index}')

出現眾數8 的位置： 4
出現眾數8 的位置： 24
出現眾數8 的位置： 27
出現眾數8 的位置： 30
出現眾數8 的位置： 35
出現眾數8 的位置： 41
出現眾數8 的位置： 43


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [ ]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


In [36]:
# ㄧ維數列，數字範圍0~10
a_list = []
for _ in range(6):
    a_list.append(random.randint(0,10))
    
print(a_list)

[6, 5, 5, 7, 0, 10]


In [38]:
#二維數列，數字範圍0~10
a_list = []
b_list = []
for _ in range(3):                             # Row
    for _ in range(4):                         # Column
        a_list.append(random.randint(0,10))
    b_list.append(a_list)
    a_list = []
b_list

[[5, 7, 5, 7], [1, 0, 4, 3], [1, 1, 9, 3]]

In [39]:
#三維數列，數字範圍0~10
a_list = []
b_list = []
c_list = []
for _ in range(2):                                 # Layer
    for _ in range(3):                             # Row
        for _ in range(2):                         # Column
            a_list.append(random.randint(0,10))
        b_list.append(a_list)
        a_list = []
    c_list.append(b_list)
    b_list = []
c_list

[[[4, 7], [9, 1], [3, 6]], [[8, 9], [10, 1], [2, 8]]]